import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "linktree elaine carriel",
  description: "Generated by tsm",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` bg-[url('background-pascoa-2.jpg')] bg-cover bg-no-repeat${inter.className}`}
      >
        {children}
      </body>
    </html>
  );
}
